project:
  type: website
  output-dir: docs

website:
  title: "calebcripe.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Resume.qmd
        text: Resume
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

