---
title: "CV"
author: "Caleb Cripe"
---

**Sustainable Communities \| Ecology \| Environmental Education**

An emerging environmental scientist with a passion for sustainable communities and environmental education. In professional settings, I bring qualities of organization and collaboration in order to work with my team effectively and efficiently. I seek to utilize my expertise in management and interpersonal relationships, and apply my core competencies of problem solving, enthusiasm, motivation, and thoroughness.

------------------------------------------------------------------------

**Education**

*Colorado State University*, Fort Collins, CO             Expected Graduation May 2026

Bachelor of Science in Ecosystem Science and Sustainability                 GPA 3.55

Double Minor in History and Sociology

Enrolled in the Honors Program

------------------------------------------------------------------------

**Work Experience**

Shift Manager, *Ben & Jerry’s  (*March 2023 – Present)

Fort Collins, CO

-       Assists with on-boarding and training of team members in shop procedures, proper service techniques, and cash handling.

-       Supervises team members and shop operations, including maintaining safety compliance, customer service, inventory, and cash register accuracy.

-       Ensures daily sales and summary reports are balanced, conducts bank deposits, and maintains confidential access to store finances.

Courtesy Clerk, *Sprouts Farmers Market  (*June 2021 – August 2022)

Fort Collins, CO

-       Properly handled customers groceries’, delivering high quality customer service as a store ambassador

-       Aided in helping customers locate products through a maintained knowledge of the store.

-       Maintained store cleanliness and ensured a smooth customer experience.

------------------------------------------------------------------------

**Ecosystem Science & Sustainability Coursework**

Honors Ecology

-       Studied interrelationships among organisms and their environments using conceptual models and quantitative approaches.

Sustainability Science

-       Learned to implement methods for understanding current issues, develop alternative scenarios to current practices and policies, and stage interventions to achieve more sustainable behaviors and practices.

------------------------------------------------------------------------

**Certifications**

Institutional Review Board (IRB) Certified                                                               February 2024 – February 2027
